services:
  db:
    image: postgres:15
    container_name: bibliotech_pg
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bibliotech
    ports:
      - "5432:5432"
    volumes:
      - bibliotech_data:/var/lib/postgresql/data
    networks:
      - bibliotech_network
  app:
    container_name: bibliotech_app
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - bibliotech_network
  proxy:
    build: proxy
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - bibliotech_network
  pgadmin:
    container_name: bibliotech_pgadmin
    image: dpage/pgadmin4:9.2
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
    networks:
      - bibliotech_network
networks:
  bibliotech_network:
    driver: bridge

volumes:
  bibliotech_data: