services:
  db:
    image: postgres:15
    container_name: bibliotech_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bibliotech
    ports:
      - "5432:5432"
    volumes:
      - bibliotech_data:/var/lib/postgresql/data
  app:
    container_name: app
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
  proxy:
    build: proxy
    restart: always
    ports:
      - 8000:80
    depends_on:
      - app
  pgadmin:
    container_name: bibliotech_pgadmin
    image: dpage/pgadmin4:9.2
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
volumes:
  bibliotech_data:
